export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';


// actions.js
export const FETCH_TASK_OPTIONS_1_REQUEST = 'FETCH_TASK_OPTIONS_1_REQUEST';
export const FETCH_TASK_OPTIONS_1_SUCCESS = 'FETCH_TASK_OPTIONS_1_SUCCESS';
export const FETCH_TASK_OPTIONS_1_FAILURE = 'FETCH_TASK_OPTIONS_1_FAILURE';

export const FETCH_TASK_OPTIONS_2_REQUEST = 'FETCH_TASK_OPTIONS_2_REQUEST';
export const FETCH_TASK_OPTIONS_2_SUCCESS = 'FETCH_TASK_OPTIONS_2_SUCCESS';
export const FETCH_TASK_OPTIONS_2_FAILURE = 'FETCH_TASK_OPTIONS_2_FAILURE';

export const FETCH_TASK_OPTIONS_3_REQUEST = 'FETCH_TASK_OPTIONS_3_REQUEST';
export const FETCH_TASK_OPTIONS_3_SUCCESS = 'FETCH_TASK_OPTIONS_3_SUCCESS';
export const FETCH_TASK_OPTIONS_3_FAILURE = 'FETCH_TASK_OPTIONS_3_FAILURE';
